Shared url navigation bug
Icinga/icingaweb2 pull request #4265
Opened 2020-11-04 10:07 UTC by sukhwinder33445

2020-11-05 07:54 UTC, nilmerg commented
Please include what this will fix in the description.

2020-11-10 20:18 UTC, lippserd commented
ref/IP/28425

2020-11-18 08:01 UTC, nilmerg requested changes
Just looked at it. I'd rather change `Icinga\Web\Url::__toString()` so that it returns a fully encoded url, not just encoded ampersands. This way any future usage does not fall into the same pit and it covers all of your changes as well already.

It's also safe to adjust Url's string casting, purely due to the fact that ampersands are already encoded there since forever. I've already used `getAbsoluteUrl()` directly due to that many times when I didn't wanted an encoded url.

Though, I'm not a fan of having this encoding in the `Icinga\Web\Url` class as it isn't its responsibility. But again, due to the ampersand being encoded this was always the case. Just not that broad so I think this is the easier fix.

2020-12-07 12:19 UTC, nilmerg approved these changes
LGTM!

2020-12-07 12:27 UTC, merged