Replace compiled Less colors with CSS var() function calls
Icinga/icingaweb2 pull request #4613
Opened 2021-12-01 13:27 UTC by lippserd

2021-12-14 14:50 UTC, nilmerg commented
By the way, this must not run for IE users. There must be a way to disable the automatism globally.

2022-02-08 23:22 UTC, lippserd commented
@nilmerg Ready to review!

2022-02-09 15:35 UTC, nilmerg requested changes
Every file is missing a license header. I thought we do this only for ipl content? Here every file has one, why should these differ?

Please fully ensure this doesn't run for IE like it's being done for Javascript [here](https://github.com/Icinga/icingaweb2/blob/master/library/Icinga/Application/webrouter.php#L71-L72).

2022-02-09 15:35 UTC, nilmerg commented on library/Icinga/Less/ColorProp.php
> +    public function setIndex(int $index)
Not compatible with PHP 5.6

2022-02-09 15:35 UTC, nilmerg commented on library/Icinga/Less/ColorProp.php
> +    public function setName(string $name)
Not compatible with PHP 5.6

2022-02-09 15:35 UTC, nilmerg commented on library/Icinga/Less/LightModeDefinition.php
> +    public function setName(string $name)
Not compatible with PHP 5.6

2022-02-09 15:35 UTC, nilmerg commented on library/Icinga/Less/ColorProp.php
> +    private function __construct()
Not compatible with PHP 5.6 (access level change)

2022-02-10 09:00 UTC, nilmerg requested changes

2022-02-10 09:00 UTC, nilmerg commented on library/Icinga/Application/webrouter.php
> +            Stylesheet::send(false, $forIe11);
`$forIe11` should ne negated, the one below as well

2022-02-10 09:44 UTC, nilmerg approved these changes

2022-02-10 09:57 UTC, nilmerg approved these changes

2022-02-10 09:58 UTC, merged