Fix dark mode variable references resolution issue
Icinga/icingaweb2 pull request #4835
Opened 2022-06-27 09:15 UTC by yhabteab

2022-06-29 07:59 UTC, nilmerg requested changes

2022-06-29 07:59 UTC, nilmerg commented on test/php/library/Icinga/Util/LessParserTest.php
> +    public function testSimpleNestedVariables()
`SimpleNested` makes no sense, it's `testNestedVariables` I'd say

2022-06-29 07:59 UTC, nilmerg commented on test/php/library/Icinga/Util/LessParserTest.php
> +@fade-color: fade(@my-color, 50%);
Please create a separate test case for this. And don't just test for the non-error, but check the result as well.

2022-06-29 11:32 UTC, sukhwinder33445 commented on library/Icinga/Less/Call.php
> +                foreach (array_reverse($env->frames) as $frame) {
$env can be null according to the parameter of the method.

2022-06-29 14:38 UTC, lippserd approved these changes

2022-06-30 09:58 UTC, nilmerg commented on library/Icinga/Less/Call.php
> +            if ($arg->value[0] instanceof Less_Tree_Variable) {
Please add the `! is_array then continue` here

2022-06-30 10:13 UTC, nilmerg submitted a review, later dismissed

2022-06-30 10:15 UTC, nilmerg approved these changes

2022-06-30 10:19 UTC, merged