Flyout menur: Render menu `bottom-up` if it exceeds the viewport height
Icinga/icingaweb2 pull request #5037
Opened 2023-06-12 11:52 UTC by sukhwinder33445

fixes #4594

2024-08-08 14:55 UTC, flourish86 requested changes
Basically it works.

I found one problem, though, which can best be seen on this screenshot:
in extreme conditions this could fire back and now exceed the top
![Screenshot 2024-08-08 at 16 44 59](https://github.com/user-attachments/assets/c732f28a-bd0c-4750-9088-2a6eb73dbe0f)

Since the items outside of the screen aren't accessible anymore in this case, this should be prevented by restricting the height and make the flyout scrollable.

I made a quick mockup for this.

![Frame 1](https://github.com/user-attachments/assets/c9771402-6fa2-4b59-91e5-4052c6fb2bf9)

While the screenshot shows the collapsed version, this problem also occurs in the expanded version of the sidebar.

![Screenshot 2024-08-08 at 16 55 56](https://github.com/user-attachments/assets/b504976c-3666-4de9-9109-784aabcd092f)

2024-08-13 09:03 UTC, sukhwinder33445 commented
Hi @flourish86,

I have discussed the problem of overflow with Johannes. It shouldn't happen in a normal screen size, and it's a different issue anyway. So for this PR we will leave it as it is.

2024-08-14 13:34 UTC, nilmerg requested changes

2024-08-14 13:34 UTC, nilmerg commented on public/js/icinga/behavior/navigation.js
> +            if (rect.bottom > window.innerHeight && rect.height < targetHeight) {
Why did you change this? Doesn't reliably work anymore for me.

2024-08-14 14:27 UTC, nilmerg approved these changes

2024-08-14 14:29 UTC, merged