Github Actions: Add PhpStan
Icinga/icingaweb2 pull request #5040
Opened 2023-06-14 09:22 UTC by sukhwinder33445

2023-07-07 07:10 UTC, nilmerg commented
Although phpstan doesn't seem to complain,
* `Icinga\Module\Monitoring\DataView\HostStatus` must be renamed to `Icinga\Module\Monitoring\DataView\Hoststatus`
* `Icinga\Module\Monitoring\DataView\ServiceStatus` must be renamed to `Icinga\Module\Monitoring\DataView\Servicestatus`

phpstan@cube complains about the first name mismatch. Though, we cannot change the class path there, as this might affect the class loading on case-sensitive file-systems. PHP is and was always case-insensitive, so changing the class name doesn't hurt that much.

2023-08-22 10:24 UTC, nilmerg requested changes

2023-08-22 11:42 UTC, sukhwinder33445 commented on modules/monitoring/application/views/helpers/Customvar.php
It is required because otherwise the methods are not defined in the given `Zend_View_Interface`.

2023-08-22 11:42 UTC, sukhwinder33445 commented on modules/monitoring/application/views/helpers/HostFlags.php
It is required because otherwise the methods are not defined in the given Zend_View_Interface.

2023-08-22 11:43 UTC, sukhwinder33445 commented on modules/monitoring/application/views/helpers/IconImage.php
> +
It is required because otherwise the methods are not defined in the given `Zend_View_Interface`.

2023-08-22 11:43 UTC, sukhwinder33445 commented on modules/monitoring/application/views/helpers/Perfdata.php
It is required because otherwise the methods are not defined in the given `Zend_View_Interface`.

2023-08-22 11:43 UTC, sukhwinder33445 commented on modules/monitoring/application/views/helpers/ServiceFlags.php
It is required because otherwise the methods are not defined in the given `Zend_View_Interface`.

2023-08-23 09:18 UTC, nilmerg requested changes

2023-08-23 09:53 UTC, merged