WIP
Icinga/icingaweb2 pull request #5052
Opened 2023-07-03 10:50 UTC by raviks789

Blocked by #5048

2023-07-10 09:02 UTC, lippserd requested changes

2023-07-10 09:21 UTC, raviks789 commented on library/Icinga/Util/LessParser.php
> +    public $importDisabled;
I did not find this property in `lessc` and if I do not introduce this property here I encountered `PHP Deprecated:  Creation of dynamic property Icinga\Util\LessParser::$importDisabled is deprecated in /icingaweb2/library/Icinga/Web/LessCompiler.php on line 66` error.

2023-07-10 09:49 UTC, lippserd commented on library/Icinga/Util/LessParser.php
> +    public $importDisabled;
So they removed the functionality to set import to disabled. Remove that property and the code setting it to false.

2023-07-13 08:36 UTC, lippserd approved these changes

2023-07-19 10:55 UTC, lippserd commented
@raviks789 Please rebase.

2023-07-19 11:11 UTC, lippserd requested changes
![localhost_icingaweb2_layout_menu](https://github.com/Icinga/icingaweb2/assets/1894563/da704a5f-173c-49b5-bd6a-c011d8e85424)

2023-07-19 11:11 UTC, lippserd commented
> ![localhost_icingaweb2_layout_menu](https://user-images.githubusercontent.com/1894563/254555333-da704a5f-173c-49b5-bd6a-c011d8e85424.png)

@raviks789 @sukhwinder33445 Is this detected/fixed somewhere by PHPStan, etc?

2023-07-19 11:39 UTC, raviks789 commented
> > ![localhost_icingaweb2_layout_menu](https://user-images.githubusercontent.com/1894563/254555333-da704a5f-173c-49b5-bd6a-c011d8e85424.png)
> 
> @raviks789 @sukhwinder33445 Is this detected/fixed somewhere by PHPStan, etc?

The dynamic properties seems to be have been identified in #5040 by PHPStan. A few of them have been fixed by  @sukhwinder33445 in the same PR. Should I move those related commits to this PR?

2023-07-19 11:55 UTC, sukhwinder33445 commented
> > ![localhost_icingaweb2_layout_menu](https://user-images.githubusercontent.com/1894563/254555333-da704a5f-173c-49b5-bd6a-c011d8e85424.png)
> 
> @raviks789 @sukhwinder33445 Is this detected/fixed somewhere by PHPStan, etc?

Yes, detected and fixed [here](https://github.com/Icinga/icingaweb2/pull/5040/commits/e4a02f913020f09284775bce217981e854863d78#diff-beff3749684c8fae946eb0c0411b44a95af7d21e7114b92f01f4db9f350ba6d6).

2023-07-19 13:59 UTC, sukhwinder33445 commented
![Screenshot 2023-07-19 at 15 54 43](https://github.com/Icinga/icingaweb2/assets/54990055/1bac0e98-6be3-4da0-b16d-d5acb9bf47f8)


## Reproduce

Call `null->getMyBug();` in any controller action and visit the url.

2023-08-21 14:20 UTC, closed without merging