Allow Enabling Strict Content Security Policy (CSP)
Icinga/icingaweb2 pull request #5059
Opened 2023-07-13 08:17 UTC by lippserd

> Content Security Policy ([CSP](https://developer.mozilla.org/en-US/docs/Glossary/CSP)) is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross-Site Scripting ([XSS](https://developer.mozilla.org/en-US/docs/Glossary/Cross-site_scripting)) and data injection attacks. These attacks are used for everything from data theft, to site defacement, to malware distribution.

([MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP))

This PR allows to enable strict CSP by introducing the following features:

* A setting to enable strict CSP in the application configuration.
* A helper class for setting/recreating/accessing nonces for dynamic CSS persisted in window-aware sessions, and for generating the CSP header.
* Logic in our base action controller that is responsible for creating the nonce and adding the CSP header when the page is first loaded or reloaded (document requests): since the first CSP header sent defines the policy, it must also contain the allowed nonces and thus cannot be deferred to Ajax responses.

Strict here means that all content must come from Icinga Web's own origin (also excluding subdomains), plus prohibiting inline JS and allowing inline CSS only if it comes with the accepted nonce.

At the moment, the only thing missing is that Icinga Web has to perform a complete page reload after changing the setting. And of course documentation.

2023-07-20 15:00 UTC, nilmerg commented on library/Icinga/Web/Controller/ActionController.php
> +            && $this->_helper->layout()->isEnabled()
In which case is it not an XHR request and without layout?

2023-07-20 15:02 UTC, nilmerg commented on library/Icinga/Web/Controller/ActionController.php
> +                $response->setHeader('X-Icinga-WindowId', $this->Window()->getId(), true);
I don't quite understand why this header is needed. It won't be processed anyway, if it's really a page load. Can you explain when/where the header is required?

2023-08-24 12:08 UTC, yhabteab commented on library/Icinga/Util/Csp.php
> +    public static function addHeader(Response $response)
```suggestion
    public static function addHeader(Response $response): void
```

2023-08-25 13:16 UTC, nilmerg requested changes

2023-08-25 13:16 UTC, nilmerg commented on application/controllers/ConfigController.php
> +            if (! $form->onSuccess()) {
Please check for false explicitly and drop the added return in the form.

2023-08-25 13:16 UTC, nilmerg commented on application/controllers/ConfigController.php
> +            return true;
shouldn't be necessary as well

2023-08-25 13:16 UTC, nilmerg commented on doc/20-Advanced-Topics.md
> +### Content Security Policy (CSP) <a id="advanced-topics-security-csp"></a>
Make this a level 2 title please. `Advanced Security` sounds weird.

2023-08-25 13:16 UTC, nilmerg commented on doc/20-Advanced-Topics.md
> +Elevate your security standards to an even higher level bei using Icinga Web 2 [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) policy.
Icinga Web ~~2~~

2023-08-25 13:16 UTC, nilmerg commented on doc/20-Advanced-Topics.md
> +Elevate your security standards to an even higher level bei using Icinga Web 2 [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) policy.
`Policy (CSP) policy.`?
Better: `Policy (CSP).`

2023-08-25 13:16 UTC, nilmerg commented on doc/20-Advanced-Topics.md
> +Enabling strict CSP can prevent your Icinga Web 2 environment from becoming a potential target of [Cross-Site Scripting (XSS)](https://developer.mozilla.org/en-US/docs/Glossary/Cross-site_scripting)
Icinga Web ~~2~~

2023-08-25 13:16 UTC, nilmerg commented on doc/20-Advanced-Topics.md
> +Enabling strict CSP can prevent your Icinga Web 2 environment from becoming a potential target of [Cross-Site Scripting (XSS)](https://developer.mozilla.org/en-US/docs/Glossary/Cross-site_scripting)
You'll get the point, I'm sure ;)

2023-08-25 14:31 UTC, nilmerg requested changes

2023-08-25 14:31 UTC, nilmerg commented on library/Icinga/Web/Controller/ActionController.php
> +            && $this->_helper->layout()->isEnabled()
To answer my own question: Static asset (e.g. images) requests and requests with the `_disableLayout` query parameter.

There are other responses without layout. Some of them include JSON or CSV content. Though some still include HTML.

So to clarify what's happening here, I'd suggest to check if the content type is `text/html` which it is only if this is true:

* Not a static asset request
* Not an api request
* Not an export

Though, to check the content type, the CSP header must not be set until the response is ready. i.e. as part of `postDispatch` (which won't be used in some of the cases above anyway)

2023-08-28 06:53 UTC, nilmerg requested changes

2023-08-28 06:53 UTC, nilmerg commented on doc/20-Advanced-Topics.md
> +Elevate your security standards to an even higher level bei using Icinga Web [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).
~~bei~~by

2023-08-28 06:53 UTC, nilmerg commented on doc/20-Advanced-Topics.md
> +Elevate your security standards to an even higher level bei using Icinga Web [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).
*by enabling the `<csp link>` for Icinga Web.*

2023-08-28 08:22 UTC, nilmerg commented on library/Icinga/Web/Controller/ActionController.php
> +            && $this->_helper->layout()->isEnabled()
Changed it. The header is now registered by the response though. https://github.com/Icinga/icingaweb2/pull/5059/commits/b96894202402950b9c3725e5f01aad4a049f6f51

2023-08-28 09:34 UTC, nilmerg commented
Creating the CSP nonce in the controller's constructor seems safe. Once the window is accessed, it's ensured an id is set. The session is also set up at this stage, as the first session access is during authentication, which is part of the bootstrapping.

2023-08-28 10:56 UTC, nilmerg requested changes

2023-08-28 10:56 UTC, nilmerg commented on doc/20-Advanced-Topics.md
> +Therefore, you have to manually enable this policy explicitly and accept the risks that this might probably break some of
~~probably~~, *might* is sufficient

2023-08-28 10:56 UTC, nilmerg commented on doc/20-Advanced-Topics.md
> +| Icinga Web GenericTTS Integration | [v2.1.0](https://github.com/Icinga/icingaweb2-module-generctts/releases/tag/v2.1.0)       |
gener**i**ctts, in the url

2023-08-28 14:15 UTC, merged