Fix `PostgreSQL` grants
Icinga/icingaweb2 pull request #5130
Opened 2023-09-28 08:39 UTC by yhabteab

fixes #5129

2023-10-06 08:04 UTC, nilmerg requested changes
Still need to test this

2023-10-09 07:47 UTC, yhabteab commented on library/Icinga/Application/MigrationManager.php
> +        if ($isPgsql && ! $tablePrivilegesGranted) {
Yes! The user must have `CREATE,CONNECT,TEMPORARY` on a database level and `CREATE,USAGE` on a schema level and must be the owner of all tables.

2023-10-09 07:50 UTC, yhabteab commented on modules/setup/application/forms/DbResourcePage.php
> -                $state = false;
This causes the wizard not to elevate the database privileges and fail to create the tables automatically.

2023-10-09 08:00 UTC, yhabteab commented on library/Icinga/Application/MigrationManager.php
> +        // PgSQL CREATE,CONNECT, and TEMPORARY privileges on a database doesn't permit a user to read data from a table
It's being checked only for `MySQL`.

2023-10-27 06:01 UTC, merged