Apply grey color to disabled toggle slider even if it's checked
Icinga/icingaweb2 pull request #5235
Opened 2024-07-19 13:40 UTC by Al2Klimov

fixes #5234

2024-07-22 10:04 UTC, flourish86 reviewed
Thanks for your review request. Could you name a view where this is in effect?

It would be helpful if you provided screenshots of before and after versions, so I can directly see the changes. Thanks in advance!

2024-07-22 10:35 UTC, Al2Klimov commented
Of course.

This is the view in question: https://plan.netways.de/icingaweb2/netrp/task/create?user=1

* It would be affected by https://github.com/Icinga/netrp/pull/131

Instead of screenshots, here is even a live view: https://minigame.prod.aklimov.net-dump.de/icingaweb2/fourcolors/demo/

2024-07-29 08:00 UTC, flourish86 requested changes
See changes in commit 43a4add

2024-08-08 07:22 UTC, nilmerg requested changes
This was solely about disabled checked sliders. Now it affects also unchecked sliders and destroys their contrast:

Before | After
---------|----
![image](https://github.com/user-attachments/assets/44473302-524e-4ba9-b914-01669df30126) | ![image](https://github.com/user-attachments/assets/745bb59d-a8a9-4dcf-8d7b-c9866b65055d)
![image](https://github.com/user-attachments/assets/24cbb428-bdd6-4057-8aa3-16f638fbaa21) | ![image](https://github.com/user-attachments/assets/64633f78-f7a0-4bd5-8b37-4f04c4c1c136)

2024-08-08 07:22 UTC, nilmerg commented on public/css/icinga/forms.less
> +.icinga-controls input[type="checkbox"]:disabled + .toggle-switch {
This was previously done with the `disabled` class.

* Why is this removed?
* Who set this to begin with?
* Is it used somewhere still?

2024-08-08 13:48 UTC, flourish86 commented
> … destroys their contrast:

I basically agree, even if I think "destroy" is a little harsh, but it was intentional. It was more of a quick fix, though.

> This was solely about disabled checked sliders. Now it affects also unchecked sliders and …

But only changing the disabled unchecked ones still doesn't solve the main problem. So, here are the main problems I was solving the "before" version:

* both the disabled ones are standing out way too much. They shouldn't since they're disabled
* both disabled toggles aren't uniformly looking "disabled" in comparison with "enabled" ones.

So what I did is add another layer for the appearance of the disabled ones, namely opacity. I agree, that especially in direct comparison to each other, this still is far from perfect (especially the light/disabled/unchecked is really low on contrast), but it's still an improvement to before.

What we probably should do to make it as good as possible is to make a refinement of alle the toggles and validate all the versions in a form context. But it would be more efficient to do that in a design tool before implementing it.

2024-08-13 13:17 UTC, nilmerg commented
>  but it's still an improvement to before.

Nah. It's blurring them so much, that I fail to identify them as toggles if buried between other elements. There's just a dark or light blob. If they keep looking this way, we can simply remove them instead of disabling them, this would have the same effect.

> But it would be more efficient to do that in a design tool before implementing it.

Then please do so.

2024-08-13 14:48 UTC, flourish86 commented
> Nah. It's blurring them so much, that I fail to identify them as toggles if buried between other elements. There's just a dark or light blob. If they keep looking this way, we can simply remove them instead of disabling them, this would have the same effect.

Sorry, but that's just subjective and random bashing without any reasoning behind it à la "I just don't like it". I explained, why it looks that way.

We won't have a final solution without either compromises or completely overhauling the theme (modes). Reducing contrast is an established way to make things disabled.

For Example

https://m2.material.io/components/text-fields#filled-text-field (See section states)

https://react.ui.audi/?path=/story/components-checkbox-all-stories--disabled

https://carbondesignsystem.com/components/toggle/usage/#states

2024-08-14 09:25 UTC, nilmerg commented
Since we don't have a final solution right now, and the suggested changes here don't reflect our final design choices, I'll close here. We'll focus on a proper solution in the future.

2024-08-14 09:25 UTC, closed without merging